services:
  postgres:
    image: postgres:16-alpine
    container_name: live-score-postgres
    environment:
      POSTGRES_DB: live_score
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d live_score"]
      interval: 10s
      timeout: 5s
      retries: 5

  live-score:
    image: arsensio/live-score:latest
    container_name: live-score-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/live_score
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/live_score
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_TOKEN_SECRET: 26452948404D6351655468576D5A7134743777217A25432A462D4A614E645267
      JWT_TOKEN_EXPIRED: 10800000
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
